---
title: "covid_phospho"
author: "Haris Babačić"
date: "2023-02-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
pack <- c("tidyverse", "ggplot2", "matrixStats", "VennDiagram", "ggrepel", "dplyr", "factoextra", "FactoMineR", "ggfortify", "cluster", "gplots", "RColorBrewer", "ComplexHeatmap", "readxl", "ggpubr", "msigdbr", "grid", "limma")
lapply(pack, require, character.only = TRUE)

setwd("code_resubmission/code")

dfna2 = read_delim("serum_phophoproteomics_ptm_peptides.txt")
dfs = read_excel("schweizer_2022_media-3.xlsx", sheet=2)
dfpep2 = read_delim("serum_phosphoproteomics_peptides_table.txt")
dfpep = dfpep2[grep("+79.966", dfpep2$`Peptide sequence`),]

df = read.csv("data_matrix.csv", row.names = 1)
labids = read.csv("labels_serum.csv", row.names = 1)

sel = grep("tmt16plex", colnames(dfna2))
sel2 = colnames(dfna2)[sel]
sel3 = sel[-grep("PSM", sel2)]

dfna2$gene_name = make.unique(dfna2$`Gene name(s)`)
dfna = as.data.frame(dfna2[,sel3])
colnames(dfna) = labids$sample_id
rownames(dfna) = dfna2$gene_name

phlab = read_excel("cell_lines_labelling.xlsx", sheet=3)
cellp2 = read_delim("peptides_phosphopeptides_ptm_peptides.txt")

head(cellp2)
sel = grep("tmt16plex_[0-9]+C$|tmt16plex_[0-9]+N$|_tmt16plex_126$", colnames(cellp2))
colnames(cellp2)[sel]
cellp = as.data.frame(cellp2[,sel])
cellp = apply(cellp, 2, as.numeric)

# Check the distribution of the data
hist(cellp, breaks=100)
boxplot(cellp)

cellp2$gene_name = make.unique(cellp2$`Gene name(s)`)
rownames(cellp) = cellp2$gene_name
colnames(cellp) = phlab$type

```

```{r get_the_locations_phosphoplus_serum, include=FALSE}

peptides = gsub("_.+", "", dfna2$`Peptide sequence`)
locs = gsub(".+_Phospho:", "", dfna2$`Peptide sequence`)
locs = gsub("S|T|Y", "", locs)

peptides2 = peptides
s = list()

for(i in 1:length(peptides2)) {
  z = locs[i]
  
  if(!is_empty(grep(",", z))) {
    s[[i]] = unlist(strsplit(z, split=","))
    for(j in s[[i]]) {
      s1 = as.numeric(j)
      substr(peptides2[i], s1, s1) = tolower(substr(peptides2[i], s1, s1))
      }
    } else {
      s[[i]] = z
      substr(peptides2[i], z, z) = tolower(substr(peptides2[i], z, z))
      }
}

mf = as.data.frame(cbind("human", peptides))
colnames(mf) = c("organism", "sequence")

write.table(mf, "for_matching_phosphositeplus.txt", row.names = F, quote=F, sep="\t")
plus = read_delim("PSP-BulkSequenceSearch.txt")

plus$Sequence = toupper(plus$Sequence)
mf2 = cbind(peptides, dfna2[,1:6], plus[match(peptides, plus$Sequence),-c(1,2)])

ph_pos = list()
for(i in 1:nrow(mf2)) {
  if(length(s[[i]])==1) {
    s1 = as.numeric(s[[i]])
    ph_pos[[i]] = paste(mf2$`Gene name(s)`[i], "_", substr(mf2$peptides[i], s1, s1), 
            mf2$`Start position`[i]+s1-1, "-p", sep="")
  } else {
    val = list()
    for(j in 1:length(s[[i]])) {
      s1 = as.numeric(s[[i]][[j]])
      val[[j]] = paste(substr(mf2$peptides[i], s1, s1), 
            mf2$`Start position`[i]+s1-1, "-p", sep="")
    }
    ph_pos[[i]] = paste(mf2$`Gene name(s)`[i], "_", paste(val, collapse=","), sep="")
  }
}

mf2$PSPlus_location = as.character(unlist(ph_pos))
str(mf2)

write.csv(mf2, "serum_phosphopeptides_located_PSPlus.csv", row.names = F)

```

```{r differential_phospho_serum, include=FALSE}
setwd("../results")

##### T test unadjusted levels #####
cov = grep("COVID", colnames(dfna))
hc = grep("HC", colnames(dfna))

miss = apply(dfna, 1, function(x) {length(which(is.na(x)))/length(x)*100})
table(miss<51)
sel = which(miss<51)

sel1 = which(dfna2$`set1_PTM FLR`>=0.05)
sel2 = which(dfna2$`set2_PTM FLR`>=0.05)
rem = union(sel1, sel2)

dfna_rem = dfna[-rem,]
dfnall = dfna_rem

res = apply(dfnall, 1, function(x) { t.test(x[cov], x[hc]) })
res2 = lapply(res, unlist)
results = as.data.frame(do.call(rbind, res2))
results$log2fc = apply(dfnall, 1, function(x) { mean(x[cov], na.rm=T)-mean(x[hc], na.rm=T) })
results$adj.p = p.adjust(results$p.value, method="fdr")
results$gene_name = rownames(dfnall)

results[,c(1:9,13,14)] = apply(results[,c(1:9,13,14)], 2, as.numeric)
results = cbind(dfna2[match(results$gene_name, dfna2$gene_name), c(1:14)], results)
results$PSPlus_location = mf2$PSPlus_location[match(results$`Peptide sequence`, mf2$`Peptide sequence`)]
res_sign = as.data.frame(results[which(results$p.value<0.05),])
max(res_sign$adj.p)

write.csv(results, "serum_phosphopeptides_all_FLR_filtered.csv")
write.csv(res_sign, "serum_phosphopeptides_not_adjusted_sign_5%_fdr_FLR_filtered.csv")

table(res_sign$`set1_PTM FLR`<0.05)
table(res_sign$`set2_PTM FLR`<0.05)
table(res_sign$`set1_q-value`<0.01)
table(res_sign$`set2_q-value`<0.01)

tres = read.csv("covid_vs_hc_all_res.csv")

```

```{r volcano_t_test, include=FALSE, echo=FALSE}
rest = results # change here depending on adjusted and non-adjusted
rest$alteration = "Up in Covid-19"
rest$alteration[which(rest$log2fc<0)] = "Down in Covid-19"

rest$shade = abs(rest$log2fc)*-log10(rest$adj.p)
cuts = as.numeric(summary(rest$shade)[-c(4)])
rest$shadcat = cut(rest$shade, breaks=cuts, include.lowest = T)
levels(rest$shadcat) = c(1:4)
table(is.na(rest$shadcat))
table(rest$shadcat)

sel = which(res_sign$`Gene name(s)` %in% c("LGALS3BP", "ORM1", "SERPINA3", "ITIH1", "GSN",
                                   "ITIH2", "SAA1", "TF", "CANX"))
# sel = which(res_sign_adj$`Gene name(s)` %in% c("LGALS3BP", "ORM1", "SERPINA3", "ITIH1", "GSN",
#                                    "ITIH2", "SAA1", "TF", "CANX"))
ressel = res_sign[which(res_sign$adj.p<0.05),]#[sel,]

y <- ressel[which(ressel$log2fc>0),]
r <- ressel[which(ressel$log2fc<0),] # change her depending on ho many you want to show to the left

cov = ggplot(rest, aes(x=log2fc, y=-log10(adj.p), col=alteration)) + 
    geom_point(aes(alpha=as.numeric(shadcat))) + 
    theme_classic() + 
    ylab(expression(paste("-log10 ", italic("q"), " values"))) + 
    xlab("log2 fold-change") + 
    scale_alpha(range=c(0.1,1), guide="none") +
    geom_hline(yintercept=-log10(0.05), col="red", linetype="dotdash", linewidth=1) + 
    geom_hline(yintercept=-log10(0.01), col="red", linetype="dotted", linewidth=1) + 
    scale_color_manual("Alteration", values=c("#0072B2", "#D55E00")) +
    #theme(legend.position = c(0.9, 0.1)) +
    theme(legend.position = "none") +
    geom_text_repel(data=y, aes(x=log2fc, y=-log10(adj.p), label=PSPlus_location), col="#D55E00", vjust=0.5, hjust=0.1) + 
    geom_text_repel(data=r, aes(x=log2fc, y=-log10(adj.p), label=PSPlus_location), col="#0072B2", vjust=0.5, hjust=-0.1) + 
    scale_x_continuous("", breaks=seq(round(min(rest$log2fc)),round(max(rest$log2fc)), 0.5)) +
    scale_y_continuous("", breaks=seq(round(min(-log10(rest$adj.p), digits=1)),
                                  round(max(-log10(rest$adj.p)), digits=1), 0.5))
cov

ggsave("volcano_serum_phospho_p<0.05_5percFDR.png", cov, width=8, height=7, units="in", dpi=600)

quartz(type = 'pdf', file = 'volcano_serum_phospho_p<0.05_5percFDR.pdf', width=8, height=7)
cov
dev.off()

```

```{r functions, include=FALSE}
difex = function (x, y, d, c) 
{
  trAFold <- rowMeans(d[, x]) - rowMeans(d[, y])
  t.result <- apply(d, 1, function(i) t.test(i[x], i[y]))
  res <- lapply(t.result, unlist)
  res = as.data.frame(do.call(rbind, res))
  res[,1:9] = apply(res[,1:9], 2, as.numeric)
  res$adj.p_values <- p.adjust(res$p.value, method = "fdr")
  results <- data.frame(Protein = rownames(d), rownam_id = rownames(d), 
                        peptide = c$`Peptide sequence`[match(rownames(d), c$gene_name)], 
                        gene_name = c$`Gene name(s)`[match(rownames(d), c$gene_name)],
                        protein_id = c$`Master protein(s)`[match(rownames(d), c$gene_name)],
                        fc = trAFold, res)
  results <- results[order(results$fc, decreasing = T), ]
  results
}

### Correct this function
volc_plot = function(x, z, a, b) {
  rest = x # change here depending on the day
  rest$alteration = "Up in Covid-19"
  rest$alteration[which(rest$fc<0)] = "Down in Covid-19"
  
  rest$shade = abs(rest$fc)*-log10(rest$adj.p)
  brk = summary(rest$shade)
  rest$shadcat = cut(rest$shade, breaks=brk, right = T)
  levels(rest$shadcat) = c(1:6)
  table(is.na(rest$shadcat))
  
  y <- rest[which(rest$shade>2.5 & rest$fc>0),]
  r <- rest[which(rest$shade>1 & rest$fc<0),] # change her depending on ho many you want to show to the left

cov = ggplot(rest, aes(x=fc, y=-log10(adj.p.value), col=alteration)) + 
    geom_point(aes(alpha=as.numeric(shadcat))) + 
    theme_classic() + 
    ylab(expression(paste("-log10 ", italic("q"), " values"))) + 
    xlab("log2 fold-change") + 
    scale_alpha(range=c(0.1,1), guide="none") +
    geom_hline(yintercept=-log10(0.05), col="red", linetype="dotdash", size=1) + 
    scale_color_manual("Alteration", values=c("#0072B2", "#D55E00")) +
    #theme(legend.position = c(0.9, 0.1)) +
    theme(legend.position = "none") +
    geom_text_repel(data=y, aes(x=fc, y=-log10(adj.p.value), label=gene_name), col="#D55E00", vjust=0.5, hjust=0.1) + 
    geom_text_repel(data=r, aes(x=fc, y=-log10(adj.p.value), label=gene_name), col="#0072B2", vjust=0.5, hjust=-0.1) + 
    scale_x_continuous("", breaks=seq(round(min(rest$fc)),round(max(rest$fc)), 0.5)) +
    scale_y_continuous("", breaks=seq(round(min(-log10(rest$adj.p.value), digits=1)),
                                  round(max(-log10(rest$adj.p.value)), digits=1), 0.25))  ### change for non-significant ones
    # scale_y_continuous("", breaks=seq(round(min(-log10(rest$adj.p.value), digits=1)),
    #                               -log10(0.05), 0.25))
cov

ggsave("volcano_inf_exp_7_day.png", cov, width=8, height=7, units="in", dpi=600)
  
  
}

```

```{r differential_phospho_cell_lines, include=FALSE}

s = list()
sel = grep("FLR", colnames(cellp2))
for(i in 1:length(sel)) {
  z = sel[i]
  s[[i]] = which(cellp2[,z]>=0.05) # 
}

s2 = unique(unlist(s))
dfsel = cellp[-s2,] 
dim(dfsel)
phall = na.omit(dfsel)
dim(phall)

mfc2 = read.csv("../data/phosphopeptides_located_PSPlus_cell_lines.csv")
mfc2$gene_name = cellp2$gene_name[match(mfc2$Peptide.sequence, cellp2$`Peptide sequence`)]

#### For 3 hours
x = grep("wt_3h", colnames(phall))
y = grep("uninf_3h", colnames(phall))

res3h = difex(x, y, phall, cellp2)
colnames(mfc2)[c(5,9:14)]
res3h = cbind(res3h, mfc2[match(res3h$gene_name, mfc2$gene_name),c(5,9:14)])
ress3h = res3h[which(res3h$adj.p_values<0.05),]

#### For day 1
x = grep("wt_1D", colnames(phall))
y = grep("uninf_1D", colnames(phall))

res1 = difex(x, y, phall, cellp2)
res1 = cbind(res1, mfc2[match(res1$gene_name, mfc2$gene_name),c(5,9:14)])
ress1 = res1[which(res1$adj.p_values<0.05),]

#### For 3 days
x = grep("wt_3D", colnames(phall))
y = grep("uninf_3D", colnames(phall))

res3 = difex(x, y, phall, cellp2)
res3 = cbind(res3, mfc2[match(res3$gene_name, mfc2$gene_name),c(5,9:14)])
ress3 = res3[which(res3$adj.p_values<0.05),]

dim(res3)

write.csv(res3, "phospho_cell_lines_day3_all_FLR_filtered.csv")
write.csv(ress3, "phospho_cell_lines_day3_all_FLR_filtered_5%FDR.csv")

#### For day 7
x = grep("wt_7D", colnames(phall))
y = grep("uninf_7D", colnames(phall))

res7 = difex(x, y, phall, cellp2)
res7= cbind(res7, mfc2[match(res7$gene_name, mfc2$gene_name),c(5,9:14)])
ress7 = res7[which(res7$adj.p_values<0.05),]

write.csv(res7, "phospho_cell_lines_day7_all_FLR_filtered.csv")
write.csv(ress7, "phospho_cell_lines_day7_all_FLR_filtered_5%FDR.csv")

```

```{r volcano_t_test_cell_lines, include=FALSE, echo=FALSE}
rest = res3 # change here the results dataset depending on the day
rest$alteration = "Up in Covid-19"
rest$alteration[which(rest$fc<0)] = "Down in Covid-19"

rest$shade = abs(rest$fc)*-log10(rest$p.value)
cuts = list()
vals = seq(0.1,1,0.15)
for(z in 1:length(vals)) {
  cuts[[z]] = quantile(rest$shade, vals[[z]]) 
}
mn = min(rest$shade)
mx = max(rest$shade)
rest$shadcat = cut(rest$shade, breaks=c(mn, cuts[-7], mx), include.lowest = T)
levels(rest$shadcat) = c(1:7)
table(is.na(rest$shadcat))
table(rest$shadcat)

sel = which(ress7$gene_name %in% c("IFIH1", "STAT1", "SP110", "LMNA", "DENND4C",
                                   "AHNAK", "TGFB1I1", "CAP1", "NPM1"))
ressel = ress3 # Change here as well depending on the day you want to see the results
sel = which(is.na(ressel$PSPlus_location))
ressel$PSPlus_location[sel] = paste(ressel$gene_name[sel], ":", gsub("_Phospho:", "", ressel$protein_id[sel]), "-p", sep="")

y <- ressel[which(ressel$fc>0),]
r <- ressel[which(ressel$fc<0),] 

cov = ggplot(rest, aes(x=fc, y=-log10(adj.p_values), col=alteration)) + 
    geom_point(aes(alpha=as.numeric(rest$shadcat))) + 
    theme_classic() + 
    ylab(expression(paste("-log10 ", italic("q"), " values"))) + 
    xlab("log2 fold-change") + 
    scale_alpha(range=c(0.1,1), guide="none") +
    geom_hline(yintercept=-log10(0.05), col="red", linetype="dotdash", size=1) + 
    #geom_hline(yintercept=-log10(0.01), col="red", linetype="dotted", size=1) + 
    scale_color_manual("Alteration", values=c("#0072B2", "#D55E00")) +
    #theme(legend.position = c(0.9, 0.1)) +
    theme(legend.position = "none") +
    geom_text_repel(data=y, aes(x=fc, y=-log10(adj.p_values), label=PSPlus_location), col="#D55E00", vjust=0.5, hjust=0.1) + 
    #geom_text_repel(data=r, aes(x=fc, y=-log10(adj.p_values), label=PSPlus_location), col="#0072B2", vjust=0.5, hjust=-0.1) + 
    scale_x_continuous("", breaks=seq(round(min(rest$fc)),round(max(rest$fc)), 0.5)) +
    scale_y_continuous("", breaks=seq(round(min(-log10(rest$adj.p_values), digits=1)),
                                  round(max(-log10(rest$adj.p_values)), digits=1), 0.25))
cov

ggsave("volcano_cells_3day_phospho_nonadjusted_5percFDR.png", cov, width=8, height=7, units="in", dpi=600)
 
quartz(type = 'pdf', file = 'volcano_cells_3day_phospho_5percFDR.pdf', width=8, height=7)
cov
dev.off()

```

```{r get_the_locations_phosphoplus_cell_lines, include=FALSE}
sel = which(cellp2$gene_name %in% rownames(phall))
peptides = gsub("_.+", "", cellp2$`Peptide sequence`[sel])
locs = gsub(".+_Phospho:", "", cellp2$`Peptide sequence`[sel])
locs = gsub("S|T|Y", "", locs)

peptides2 = peptides
s = list()

for(i in 1:length(peptides2)) {
  z = locs[i]
  
  if(!is_empty(grep(",", z))) {
    s[[i]] = unlist(strsplit(z, split=","))
    for(j in s[[i]]) {
      s1 = as.numeric(j)
      substr(peptides2[i], s1, s1) = tolower(substr(peptides2[i], s1, s1))
      }
    } else {
      s[[i]] = z
      substr(peptides2[i], z, z) = tolower(substr(peptides2[i], z, z))
      }
}

mfc = as.data.frame(cbind("human", peptides))
colnames(mfc) = c("organism", "sequence")

write.table(mfc, "../data/for_matching_phosphositeplus_cell_lines.txt", row.names = F, quote=F, sep="\t")

plist = list()
for(i in c(1:5)) {
  val = read.delim(paste("../data/cells_PSP-BulkSequenceSearch_", i, ".txt", sep=""), row.names = NULL)
  colnames(val) = colnames(val)[2:9]
  plist[[i]] = val[,-9]
}

plusc = do.call(rbind, plist)

plusc$Sequence = toupper(plusc$Sequence)
mfc2 = cbind(peptides, cellp2[sel,1:6], plusc[match(peptides, plusc$Sequence),-c(1,2)])

ph_pos = list()
for(i in 1:nrow(mfc2)) {
  if(length(s[[i]])==1) {
    s1 = as.numeric(s[[i]])
    ph_pos[[i]] = paste(mfc2$`Gene name(s)`[i], "_", substr(mfc2$peptides[i], s1, s1), 
            mfc2$Start.position[i]+s1-1, "-p", sep="")
  } else {
    val = list()
    for(j in 1:length(s[[i]])) {
      s1 = as.numeric(s[[i]][[j]])
      val[[j]] = paste(substr(mfc2$peptides[i], s1, s1), 
            mfc2$Start.position[i]+s1-1, "-p", sep="")
    }
    ph_pos[[i]] = paste(mfc2$`Gene name(s)`[i], "_", paste(val, collapse=","), sep="")
  }
}

mfc2$PSPlus_location = as.character(unlist(ph_pos))
str(mfc2)

write.csv(mfc2, "phosphopeptides_located_PSPlus_cell_lines.csv", row.names = F)

```

```{r locate_peptides, include=FALSE}
library(biomaRt)
library(bioseq)

prot_sel = unique(gsub("[.].+", "", res_sign$gene_name))
res_sel = res_sign
res_sel$peptide = dfna2$`Peptide sequence`[match(res_sel$gene_name, dfna2$gene_name)]
res_sel$phospho_loc = gsub(".+_Phospho:", "", res_sel$peptide)
res_sel$peptide = gsub("_.+", "", res_sel$peptide)

mart <- useMart("ensembl", dataset="hsapiens_gene_ensembl")

prot_seqs = getSequence(id = prot_sel, 
            type = "hgnc_symbol", 
            seqType = "peptide", 
                  mart = mart)
prot_seqs$peptide = gsub("[*]", "", prot_seqs$peptide)
prot_seqs$length = nchar(prot_seqs$peptide)

prot_seqs$uniq_id =  make.unique(prot_seqs$hgnc_symbol)

pos = list()
for(i in prot_seqs$uniq_id) {
  s = gsub("[.].+", "", i)
  sel_res = res_sel[grep(s, res_sel$gene_name),]
  ai = prot_seqs$peptide[which(prot_seqs$uniq_id==i)]
  
  poss = list()
  for(z in 1:nrow(sel_res)) {
  poss[[z]] = unlist(str_locate_all(ai, sel_res$peptide[z]))
  
  if(is_empty(poss[[z]])==T) {
    poss[[z]] = c(NA, NA)
  } else {
    poss[[z]] = poss[[z]]
  }
  
  }
  
  pos[[i]] = do.call(rbind, poss)
  rownames(pos[[i]]) = paste(sel_res$gene_name, "in", i, sep="_")
  colnames(pos[[i]]) = c("start", "end")

}

matches = as.data.frame(do.call(rbind, pos))
matches$gene_id = gsub("_.+", "", rownames(matches))
matches$prot_isoform = gsub(".+_in_", "", rownames(matches))
matches$peptide = res_sel$peptide[match(matches$gene_id, res_sel$gene_name)]

```

```{r overlap_schweizer_dataset, include=FALSE}
intersect(dfs$Gene.symbol, dfna2$`Gene name(s)`)
intersect(dfs$Gene.symbol, cellp2$`Gene name(s)`)
library(bioseq)

dfna2$peptide = gsub("_.+", "", dfna2$`Peptide sequence`)
seqs = unique(dfna2$peptide)

ressel = res3h$Protein[which(res3h$p.value<0.05)]
cellp2$peptide = gsub("_.+", "", cellp2$`Peptide sequence`)
seqs = unique(cellp2$peptide[which(cellp2$gene_name %in% ressel)])

schwm = list()
x = aa(unique(dfs$Sequence))
for(i in seqs) {
  schwm[[i]] = seq_detect_pattern(x, i)
}
schw_r = lapply(schwm, function(z) any(z==T))
table(unlist(schw_r))
sel = which(unlist(schw_r)==T)

View(dfs[which(dfs$Sequence %in% names(sel)),])
View(cellp2[which(cellp2$peptide %in% names(sel)),])

```

```{r overlap_our_phospho, include=FALSE}
sel = unique(cellp2$`Gene name(s)`)
sel2 = unique(dfna2$`Gene name(s)`)

selp = intersect(sel, sel2)
ressel = cellp2[which(cellp2$`Gene name(s)` %in% selp),]
ressel2 = dfna2[which(dfna2$`Gene name(s)` %in% selp),]

ressel$peptide = gsub("_.+", "", ressel$`Peptide sequence`)
ressel2$peptide = gsub("_.+", "", ressel2$`Peptide sequence`)

pos = list()
for(i in ressel2$gene_name) {
  s = gsub("[.].+", "", i)
  sel_res = ressel[grep(s, ressel$`Gene name(s)`),]
  ai = ressel2$peptide[which(ressel2$gene_name==i)]
  
  poss = list()
  for(z in 1:nrow(sel_res)) {
  poval = unlist(str_locate_all(ai, sel_res$peptide[z]))
  
  if(is_empty(poval)==T) {
    poss[[z]] = c(NA, NA)
  } else {
    poss[[z]] = poval
  }
  
  }
  
  pos[[i]] = do.call(rbind, poss)
  rownames(pos[[i]]) = paste(i, "in", sel_res$gene_name, sep="_")
  colnames(pos[[i]]) = c("start", "end")

}

matches2 = do.call(rbind, pos)
matches2 = na.omit(matches2)

pos = list()
for(i in ressel$gene_name) {
  s = gsub("[.].+", "", i)
  sel_res = ressel2[grep(s, ressel2$`Gene name(s)`),]
  ai = ressel$peptide[which(ressel$gene_name==i)]
  
  poss = list()
  for(z in 1:nrow(sel_res)) {
  posval = unlist(str_locate_all(ai, sel_res$peptide[z]))
  
  if(is_empty(posval)==T) {
    poss[[z]] = c(NA, NA)
  } else {
    poss[[z]] = posval
  }
  
  }
  
  pos[[i]] = do.call(rbind, poss)
  rownames(pos[[i]]) = paste(i, "in", sel_res$gene_name, sep="_")
  colnames(pos[[i]]) = c("start", "end")
}

matches3 = do.call(rbind, pos)
matches3 = na.omit(matches3)

View(matches2)
sel = match(gsub("_.+", "", rownames(matches2)), dfna2$gene_name)
sel2 = match(gsub(".+_in_", "", rownames(matches3)), dfna2$gene_name)
# Only for plasma
plamat = dfna2$gene_name[sel]
# Matching both ways
plamat = c(dfna2$gene_name[sel], dfna2$gene_name[sel2])

sel = match(gsub(".+_in_", "", rownames(matches2)), ressel$gene_name)
sel2 = match(gsub("_.+", "", rownames(matches3)), ressel$gene_name)
# Only for plasma
cellmat = ressel$gene_name[sel]
# Matching both ways
cellmat = c(ressel$gene_name[sel], ressel$gene_name[sel2])

mdf = as.data.frame(cbind(cellmat, plamat))
mdf$cell_peptide = cellp2$`Peptide sequence`[match(mdf$cellmat, cellp2$gene_name)]
mdf$plasma_peptide = dfna2$`Peptide sequence`[match(mdf$plamat, dfna2$gene_name)]
mdf$cellpep_flank_seq = cellp2$`Matching gene count`[match(mdf$cellmat, cellp2$gene_name)]
mdf$plasma_flank_seq = dfna2$`Matching gene count`[match(mdf$plamat, dfna2$gene_name)] 
table(mdf$cell_peptide==mdf$plasma_peptide)
table(mdf$cellpep_flank_seq==mdf$plasma_flank_seq)

sel1 = which(duplicated(mdf$cell_peptide)==T)
sel2 = which(duplicated(mdf$plasma_peptide)==T)
rem = intersect(sel1, sel2)

mdf2 = mdf[-rem,]
table(mdf2$cell_peptide==mdf2$plasma_peptide)
table(mdf2$cellpep_flank_seq==mdf2$plasma_flank_seq)

length(unique(mdf2$cell_peptide))
length(unique(mdf2$plasma_peptide))

sel = which(mdf2$cellpep_flank_seq==mdf2$plasma_flank_seq)
View(mdf2[sel,])
sel = which(mdf2$cell_peptide==mdf2$plasma_peptide)
View(mdf2[sel,])

```

```{r boxplots, include=FALSE}
library(ggpubr)
library(cowplot)

af = cellp
dfaf = dfna

# Always start with the cell lines
selected = cellmat
sel = which(selected %in% rownames(phall))
selected = selected[sel]

sel = unique(c(ress3h$Protein, ress1$Protein, ress3$Protein, ress7$Protein))
selected[which(selected %in% sel)]

sels = selected[grep("CANX.", selected)]
i = "CANX.10" # this one matches with CANX.1 in serum

for (i in selected) {
  gr = c("uninf_3D", "wt_UV_3D", "wt_3D", "wt_7D")
  gr2 = c("COV", "HC")
  
  sel = c(grep("uninf_3h", colnames(af)), grep("wt_UV_3h", colnames(af)), grep("wt_3h", colnames(af)),
        grep("uninf_1D", colnames(af)), grep("wt_UV_1D", colnames(af)), grep("wt_1D", colnames(af)),
        grep("uninf_3D", colnames(af)), grep("wt_UV_3D", colnames(af)), grep("wt_3D", colnames(af)),
        grep("uninf_7D", colnames(af)), grep("wt_UV_7D", colnames(af)), grep("wt_7D", colnames(af)))
  vals = af[i, sel]
  
  cats = c(rep("uninf_3h", 3), rep("wt_UV_3h", 3), rep("wt_3h", 3),
        rep("uninf_1D", 3), rep("wt_UV_1D", 3), rep("wt_1D", 3),
        rep("uninf_3D", 3), rep("wt_UV_3D", 3), rep("wt_3D", 3),
        rep("uninf_7D", 3), rep("wt_UV_7D", 3), rep("wt_7D", 3))
  bc = as.data.frame(cbind(vals, cats))
  bc$vals = as.numeric(bc$vals)
  
  mycomparisons = list(c("wt_3h", "wt_UV_3h"), c("wt_3h", "uninf_3h"),
                     c("wt_1D", "wt_UV_1D"), c("wt_1D", "uninf_1D"),
                     c("wt_3D", "wt_UV_3D"), c("wt_3D", "uninf_3D"),
                     c("wt_7D", "wt_UV_7D"), c("wt_7D", "uninf_7D"),
                     c("wt_3h", "wt_1D"),
                     c("wt_1D", "wt_3D"),
                     c("wt_3D", "wt_7D"))
  
  cols = rep(c("black",  "#009E73", "#D55E00"), 4)
  
  bc$Condition = factor(gsub("_[0-9].+", "", bc$cats), levels=c("uninf", "wt_UV", "wt"))
  levels(bc$Condition) = c("Uninfected", "UV Mock", "SARS-CoV-2")
  
  pep = cellp2$`Peptide sequence`[which(cellp2$gene_name==i)]
  
  p1 = ggboxplot(bc, x="cats", y="vals", color="Condition",
          add="jitter", palette=cols, size=0.25) +
  stat_compare_means(comparisons = mycomparisons, 
                     label = "p.signif", method="t.test",
                     label.y=c(max(bc$vals[grep("3h", bc$cats)])+0.4,
                               max(bc$vals[grep("3h", bc$cats)])+0.1,
                               max(bc$vals[grep("1D", bc$cats)])+0.4,
                               max(bc$vals[grep("1D", bc$cats)])+0.1,
                               max(bc$vals[grep("3D", bc$cats)])+0.4,
                               max(bc$vals[grep("3D", bc$cats)])+0.1,
                               max(bc$vals[grep("7D", bc$cats)])+0.4,
                               max(bc$vals[grep("7D", bc$cats)])+0.1)) +
  scale_x_discrete("Group", breaks=c("wt_UV_3h", "wt_UV_1D", "wt_UV_3D", "wt_UV_7D"), 
                   labels=c("3 hours", "1 day", "3 days", "7 days")) +
  scale_y_continuous("log2 relative expression values (ratios)") +
  geom_vline(xintercept = c(3.5, 6.5, 9.5), linetype="dashed", color="#999999") + 
  theme(legend.position="none") #+
  #ggtitle(paste("Protein:", gsub("[.].+", "", i), ", Phosphopeptide:", pep))
  p1
  
  seq = cellp2$`Matching gene count`[which(cellp2$gene_name==i)]
  i2 = dfna2$gene_name[which(dfna2$`Matching gene count`==seq)]
  
  a = gsub("[0-9]+", "", colnames(dfaf[i2,]))
  bp = as.data.frame(cbind(as.numeric(dfaf[i2,]), a))
  bp = bp[-grep("IS", bp$a),]
  
  bp$V1 = as.numeric(bp$V1)
  bp$V2 = factor(bp$a, levels=c("HC", "COVID"))
  levels(bp$V2) = c("Healthy", "COVID-19")
  
  p2 = ggboxplot(bp, x="V2", y="V1", color="V2",
          add="jitter", palette = cols[-1]) +
  stat_compare_means(method="t.test", label = "p.format") +
  xlab("Group") +
  scale_y_continuous("log2 relative expression values (ratios)") +
  theme(legend.position="none")
  p2
  
  pp = plot_grid(p1, p2,
          rel_widths = c(2,1))
  pp
  
  pps = mf2$PSPlus_location[match(pep, mf2$`Peptide sequence`)]
  
  ggsave(paste("cell_plasma_phospho_plot/gene_", i, "_in_", i2, "--",
               pep, "--PPSloc;;", pps, ";;cell_serum_plot.pdf", sep=""), pp, 
         dpi=300, width=7, height=3.5)
  print(paste("Run", which(selected==i), ": Protein", i, "done."))
}

```

